In [1]:
import numpy as np

(A)

\begin{equation}
\frac{V_1-V_+}{R} + \frac{V_1-V_2}{R} + \frac{V_1-V_3}{R} = 0 \iff 3V_1 - V_2 - V_3 = V_+
\end{equation}

\begin{equation}
\frac{V_2-V_+}{R} + \frac{V_2-V_1}{R} + \frac{V_2-V_3}{R} + \frac{V_2-V_4}{R} = 0 \iff 4V_2 - V_1 - V_3 - V_4 = V_+
\end{equation}

\begin{equation}
\frac{V_3-V_1}{R} + \frac{V_3-V_2}{R} + \frac{V_3-V_4}{R} + \frac{V_3-V_5}{R} = 0 \iff 4V_3 - V_1 - V_2 - V_4 - V_5 = 0
\end{equation}

\begin{equation}
\frac{V_i-V_{i-2}}{R} + \frac{V_i-V_{i-1}}{R} + \frac{V_i-V_{i+1}}{R} + \frac{V_i-V_{i+2}}{R} = 0 \iff 4V_i - V_{i-2} - V_{i-1} - V_{i+1} - V_{i+2} = 0
\end{equation}

\begin{equation}
\frac{V_{N-1}-V_{N-2}}{R} + \frac{V_{N-1}-V_{N}}{R} + \frac{V_{N-1}-V_{N-3}}{R} + \frac{V_{N-1}-0}{R} = 0 \iff 4V_{N-1} - V_{N-3} - V_{N-2} - V_{N} = 0
\end{equation}

\begin{equation}
\frac{V_{N}-V_{N-2}}{R} + \frac{V_{N}-V_{N-1}}{R} + \frac{V_{N}-0}{R} = 0 \iff 3V_{N} - V_{N-2} - V_{N-1} = 0
\end{equation}

In matrix form: (N=6)

\begin{gather}
\begin{pmatrix}
3 & -1 & -1 & 0 & 0 & 0\\
-1 & 4 & -1 & -1 & 0 & 0\\
-1 & -1 & 4 & -1 & -1 & 0\\
0 & -1 & -1 & 4 & -1 & -1\\
0 & 0 & -1 & -1 & 4 & -1\\
0 & 0 & 0 & -1 & -1 & 3
\end{pmatrix} 
\begin{pmatrix}
V_1\\
V_2\\
V_3\\
V_4\\
V_5\\
V_6
\end{pmatrix} = 
\begin{pmatrix}
V_+\\
V_+\\
0\\
0\\
0\\
0
\end{pmatrix}
\end{gather}

(B)

In [2]:
#Constants:
v_plus = 5
N = 6

In [3]:
A = np.zeros ([N , N] , dtype = float)
v = np.array ([v_plus , v_plus , 0 , 0 , 0 , 0] , dtype = float)

for row in range (1 , N-1):
    A[row,row] = 4
for row in range (N-1):
    A[row,row+1] = -1
    A[row+1,row] = -1
for row in range (N-2):
    A[row,row+2] = -1
    A[row+2,row] = -1
    
A[0,0] , A[N-1,N-1] = 3 , 3
print (' A =' , A ,'\n\n', 'v =', v)

 A = [[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]] 

 v = [5. 5. 0. 0. 0. 0.]


In [4]:
#Gaussian elimination:

#For the first row:
div = A[0,0]
A[0,:3] /= div
v[0] /= div

mult = A[1,0]
A[1,:4] -= mult*A[0,:4]
v[1] -= mult*v[0]

mult = A[2,0]
A[2,:5] -= mult*A[0,:5]
v[2] -= mult*v[0]

#For the second row:
div = A[1,1]
A[1,:4] /= div
v[1] /= div

mult = A[2,1]
A[2,1:5] -= mult*A[1,1:5]
v[2] -= mult*v[1]

mult = A[3,1]
A[3,1:6] -= mult*A[1,1:6]
v[3] -= mult*v[1]

#For the third and fourth rows:
for row in range (2,4):
    div = A[row,row]
    A[row,:row+3] /= div
    v[row] /= div
    
    for i in range (row+1,row+3):
        mult = A[i,row]
        A[i,i-2:i+3] -= mult*A[row,i-2:i+3]
        v[i] -= mult*v[row]
        
        
#For the fifth row:
div = A[4,4]
A[4,:] /= div
v[4] /= div

mult = A[5,4]
A[5,:] -= mult*A[4,:]
v[5] -= mult*v[4]

#For the sixth row:
A[N-1,N-1] /= A[N-1,N-1]
v[N-1] /= A[N-1,N-1]

In [5]:
x = np.empty (N , dtype = float)
x[N-1] = v[N-1]
x[N-2] = v[N-2] - A[N-2,N-1]*v[N-1]
for row in range (N-2):
    x[row] = v[row] - A[row,row+1]*v[row+1] - A[row,row+2]*v[row+2]
    
print (x)   

[2.7012987  2.59563164 2.07383933 2.37683723 2.1700312  2.52994012]


In [ ]:
''' Eu resolvi as equações à mão e cheguei aos cálculos que apresento na célula acima. 
    A minha dúvida é se devia ter usado backsubstitution,
    porque penso que resolvi bem o método de gauss para uma matriz com 5 diagonais, 
    mas o resultado dá diferente do obtido usando o linalg como se pode verificar abaixo.'''

In [7]:
A = np.zeros ([N , N] , dtype = float)
v = np.array ([v_plus , v_plus , 0 , 0 , 0 , 0] , dtype = float)

for row in range (1 , N-1):
    A[row,row] = 4
for row in range (N-1):
    A[row,row+1] = -1
    A[row+1,row] = -1
for row in range (N-2):
    A[row,row+2] = -1
    A[row+2,row] = -1
    
A[0,0] , A[N-1,N-1] = 3 , 3

print (np.linalg.solve (A,v))

[3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]
