In [9]:
import numpy as np

(A)

To prove that $q_i \cdot q_i = 1$, we can just look at the definition of $q_i$:

\begin{equation}
q_i \cdot q_i = \frac{u_i}{|u_i|} \cdot \frac{u_i}{|u_i|} = \frac{1}{|u_i|^{2}} (u_i\cdot u_i) = \frac{1}{|u_i|^{2}} |u_i|^{2} = 1
\end{equation}

To prove that $q_i \cdot q_j = 0$ for $i \neq j$ we can begin to prove that $u_i \cdot u_j = 0$.

So, if

\begin{equation}
0 = u_i \cdot u_j = u_i \cdot \frac{u_j}{|u_j|} = u_i \cdot q_j
\end{equation}

And so,

\begin{equation}
u_i \cdot q_j = a_i \cdot q_j - \sum (q_j \cdot a_i)q_j \cdot q_j = a_i \cdot q_j - \sum (q_j \cdot a_i) = 0
\end{equation}

(B)

In [10]:
def QR_decomp (A):
    
    N = len (A)
    
    Q = np.zeros ([N,N] , dtype=float) #This is an orthogonal matrix and
    R = np.zeros ([N,N] , dtype=float) #this is an upper triagonal matrix satisfying A=QR.


    for col in range (N):
        u = np.copy (A[:,col])
        for i in range (col):
            u -= np.dot(Q[:,i] , A[:,col]) * Q[:,i]
        Q[:,col] = u / np.linalg.norm(u)
        
    for row in range (N):
        for col in range (row , N):
            R[row,col] = np.dot (Q[:,row] , A[:,col])
               
    return Q , R

In [11]:
A = np.array ([[1,4,8,4],
              [4,2,3,7],
              [8,3,6,9],
              [4,7,9,2]] , dtype=float)

Q , R = QR_decomp (A)
print (' Q = ', '\n' , Q , '\n\n' , 'R = ', '\n' , R ,'\n\n' , 'A = ', '\n' , np.matmul(Q,R))

 Q =  
 [[ 0.10153462  0.558463    0.80981107  0.1483773 ]
 [ 0.40613847 -0.10686638 -0.14147555  0.8964462 ]
 [ 0.81227693 -0.38092692  0.22995024 -0.37712564]
 [ 0.40613847  0.72910447 -0.5208777  -0.17928924]] 

 R =  
 [[ 9.8488578   6.49821546 10.55960012 11.37187705]
 [ 0.          5.98106979  8.4234836  -0.484346  ]
 [ 0.          0.          2.74586406  3.27671222]
 [ 0.          0.          0.          3.11592335]] 

 A =  
 [[1. 4. 8. 4.]
 [4. 2. 3. 7.]
 [8. 3. 6. 9.]
 [4. 7. 9. 2.]]


(C)

In [14]:
def accuracy_test (epsilon , M):
    
    ''' This program returns True if the off-diagonal elements of matrix M are lower than epsilon
        and False if they are not. '''
    
    N = len(M)
    
    for row in range (N):
        for col in range (N):
            if row == col:
                continue
            else:
                if abs(M[row,col]) >= epsilon:
                    return False
    return True

In [15]:
def QR_algorithm (A , epsilon):
    
    N = len(A)
    
    #This matrix will hold the eigenvectors of A. It starts off as the identity matrix:
    V = np.eye (N , dtype=float)
    
    while accuracy_test (epsilon , A) == False:
        Q , R = QR_decomp (A)
        A = np.matmul (R,Q)
        V = np.matmul (V,Q)
    
    eigenvals = np.zeros (N , dtype=float)
    for row in range (N):
        eigenvals[row] = A[row,row]
    
    return eigenvals , V

In [17]:
A = np.array ([[1,4,8,4],
              [4,2,3,7],
              [8,3,6,9],
              [4,7,9,2]] , dtype=float)

eigenval , eigenvec = QR_algorithm (A , 1e-6)
print (eigenval , '\n\n' , eigenvec)

[21. -8. -3.  1.] 

 [[ 0.43151698 -0.38357064 -0.77459666 -0.25819889]
 [ 0.38357063  0.43151698 -0.2581989   0.77459667]
 [ 0.62330228  0.52740965  0.25819889 -0.51639778]
 [ 0.52740965 -0.62330227  0.51639779  0.25819889]]
